---
kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: everything
  image: letfn/drone-kaniko
  settings:
    args: --verbosity=info
    cache: true
    cache_repo: letfn/cache
    password:
      from_secret: docker_password
    repo: letfn/drone-kaniko
    skip_tls_verify: true
    tag: latest
    username:
      from_secret: docker_username

---
kind: pipeline
type: docker
name: fmt

platform:
  os: linux
  arch: amd64

steps:
- name: everything
  image: letfn/container
  commands:
  - drone fmt --save
  - drone fmt --save .drone.yml.build

---
kind: pipeline
type: docker
name: lint

platform:
  os: linux
  arch: amd64

steps:
- name: everything
  image: letfn/container
  commands:
  - drone lint
  - drone lint .drone.yml.build

---
kind: pipeline
type: docker
name: docs

platform:
  os: linux
  arch: amd64

steps:
- name: local
  image: letfn/drone-hugo

- name: gh-pages
  image: letfn/drone-hugo
  settings:
    github_pages: true

...
