---
kind: pipeline
type: docker
name: build-a

platform:
  os: linux
  arch: amd64

steps:
- name: everything
  image: letfn/drone-kaniko
  settings:
    cache: true
    password:
      from_secret: docker_password
    cache_repo: letfn/cache
    repo: letfn/drone-kaniko
    skip_tls_verify: true
    username:
      from_secret: docker_username
    tag: a

---
kind: pipeline
type: docker
name: fmt

platform:
  os: linux
  arch: amd64

steps:
- name: everything
  image: letfn/container
  commands:
  - drone fmt --save
  - drone fmt --save .drone.yml.build

---
kind: pipeline
type: docker
name: lint

platform:
  os: linux
  arch: amd64

steps:
- name: everything
  image: letfn/container
  commands:
  - drone lint --trusted
  - drone lint .drone.yml.build

---
kind: pipeline
type: docker
name: docs

platform:
  os: linux
  arch: amd64

steps:
- name: local
  image: letfn/drone-hugo
  commands:
  - cp config.yaml.template config.yaml
  - hugo
  - rm -f config.yaml

- name: gh-pages
  image: letfn/drone-hugo
  commands:
  - "(cat config.yaml.template; echo; echo uglyurls: false; echo publishDir: gh-pages) > config.yaml"
  - hugo
  - rm -f config.yaml

...
