#!/bin/sh

function main {
  set -eu

  mv /bin/* /kaniko/
  rmdir /bin || rm /bin || true

  set -f

  registry="${PLUGIN_REGISTRY:-index.docker.io}"

  auth="$(echo -n "${PLUGIN_USERNAME}:${PLUGIN_PASSWORD}" | base64 | tr -d "\n")"
  mkdir -p /kaniko/.docker
  cat > /kaniko/.docker/config.json <<EOF
{
  "auths": {
    "${registry}": {
      "auth": "${auth}"
    },
    "https://${registry}/v1/": {
      "auth": "${auth}"
    }
  }
}
EOF

  set -x

  /kaniko/executor \
    --context=${PLUGIN_CONTEXT:-${PWD}} \
    --dockerfile=${PLUGIN_DOCKERFILE:-Dockerfile} \
    ${PLUGIN_CACHE_REPO:+--cache-repo=${PLUGIN_CACHE_REPO}} \
    --cache=${PLUGIN_CACHE:-false} ${PLUGIN_ARGS:-} \

  set +x

  if [[ -f benchmark/build.json ]]; then
    cat benchmark/build.json | jq -r 'to_entries | map(.value = (.value/1000000/1000 | tostring | split(".")[0] | tonumber))[] | "\(.value) \(.key)"' \
      | sort -n | while read -r a b; do printf '%5s %s\n' "$a" "$b"; done
  fi
}

main "$@"
