#!/bin/sh

function main {
  set -eu

  mv /bin/* /kaniko/
  rmdir /bin

  set -f

  registry="${PLUGIN_REGISTRY:-index.docker.io}"

  auth="$(echo -n "${PLUGIN_USERNAME}:${PLUGIN_PASSWORD}" | base64 | tr -d "\n")"
  mkdir -p /kaniko/.docker
  cat > /kaniko/.docker/config.json <<EOF
{
  "auths": {
    "${registry}": {
      "auth": "${auth}"
    },
    "https://${registry}/v1/": {
      "auth": "${auth}"
    }
  }
}
EOF

  set -x

  /kaniko/executor \
    --reproducible \
    --cache=true \
    --context=${PLUGIN_CONTEXT:-${PWD}} \
    --dockerfile=${PLUGIN_DOCKERFILE:-Dockerfile} \
    --cache-repo=${registry}/${PLUGIN_CACHE_REPO} \
    --destination=${registry}/${PLUGIN_REPO}:${PLUGIN_TAG} ${PLUGIN_ARGS:-}

  echo "done"
}

main "$@"
